### ISSUE TITLE
pnpm

### ISSUE THREAD

**Issue by mokone91** [beforeyoubid/serverless-webpack-layers#23]
Do you plan to add pnpm support?

**Comment by ghost** [comment]
Thank you for raising the issue!

I have opened a PR to add pnpm support for the packager config (which currently only supports yarn & npm)

I am not familiar with pnpm commands/workflow, so I will seek to publish as a pre-release version to test internally before publishing a new minor version.

Will update the issue w/ progress!

**Comment by ghost** [comment]
Should be live now on npm w/ support in version 2.1.0.

this will require setting `layerConfig.packager` to `pnpm`
